version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123456
    ports:
      - "1434:1434"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init-db:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 30 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 123456 -d master -i /usr/src/app/hr.sql
volumes:
  sql_data:
